name: Checking modified files in PR with pylint

on:
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Install GitHub CLI
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
          && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
          
      - name: Set status to success
        if: success()
        run: |
          gh api -X POST \
            repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state=success \
            -f context="Checking modified files in PR with pylint" \
            -f description="Pylint checks passed" \
            -f target_url="${{ github.event.pull_request.html_url }}"       

      - name: Set status to failure
        if: failure()
        run: |
          gh api -X POST \
            repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state=failure \
            -f context="Checking modified files in PR with pylint" \
            -f description="Pylint checks failed" \
            -f target_url="${{ github.event.pull_request.html_url }}"
