name: Checking modified files in PR with pylint

on:
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.PYLINT_TOKEN }}
